  pull_request_rules:
    - name: Auto-merge Dependabot PRs (main)
      conditions:
        - author = dependabot[bot]
        - base = main
        - check-success = build
        - check-success = Analyze (java)
        - check-success = Analyze (python)
      actions:
        queue:
          name: default

    - name: Auto-merge Dependabot PRs (5.x.x-stable)
      conditions:
        - author = dependabot[bot]
        - base = 5.x.x-stable
        - check-success = build
        - check-success = Analyze (java)
        - check-success = Analyze (python)
      actions:
        queue:
          name: default

    - name: Auto-merge on label (main)
      conditions:
        - base = main
        - label = automerge
        - check-success = build
        - check-success = Analyze (java)
        - check-success = Analyze (python)
      actions:
        queue:
          name: default

    - name: Auto-merge on label (5.x.x-stable)
      conditions:
        - base = 5.x.x-stable
        - label = automerge
        - check-success = build
        - check-success = Analyze (java)
        - check-success = Analyze (python)
      actions:
        queue:
          name: default

    - name: Automatically backport to 5.x.x-stable
      conditions:
        - base = main
        - label = backport-v5.x.x
      actions:
        backport:
          branches:
            - 5.x.x-stable
          assignees:
            - "{{ author }}"

  queue_rules:
    - name: default
      merge_method: merge
