#!/bin/sh

set -e

SCRIPTDIR=$(dirname "$0")
SRCDIR=$(cd "$SCRIPTDIR"/.. && pwd)

(
	cd "$SRCDIR"
	mvn -q test-compile -P '!setup-test-cluster'
	mvn -q exec:java \
		-Dexec.classpathScope=test \
		-Dexec.mainClass="com.rabbitmq.examples.PerfTest" "$@"
)
