name: Test against supported Java versions (5.x)

on:
  schedule:
    - cron: '0 4 ? * SUN,THU'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        distribution: [ 'temurin' ]
        version: [ '8', '11', '17', '21', '23', '24-ea' ]
        include:
          - distribution: 'semeru'
            version: '17'
    name:  Test against Java ${{ matrix.distribution }} ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: 5.x.x-stable
      - name: Checkout tls-gen
        uses: actions/checkout@v5
        with:
          repository: rabbitmq/tls-gen
          path: './tls-gen'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.version }}
          cache: 'maven'
      - name: Start broker
        run: ci/start-broker.sh
      - name: Get dependencies
        run: make deps
      - name: Show version
        run: ./mvnw --version
      - name: Test with NIO
        run: |
          ./mvnw verify -Dio.layer=netty -Drabbitmqctl.bin=DOCKER:rabbitmq \
            -Dtest-broker.A.nodename=rabbit@$(hostname) -Dmaven.javadoc.skip=true \
            -Dca.certificate=./tls-gen/basic/result/ca_certificate.pem \
            -Dclient.certificate=./tls-gen/basic/result/client_$(hostname)_certificate.pem \
            -Dit.test=ClientTestSuite,FunctionalTestSuite,ServerTestSuite,SslTestSuite \
            --no-transfer-progress
      - name: Test with blocking IO
        run: |
          ./mvnw verify -Dio.layer=socket -Drabbitmqctl.bin=DOCKER:rabbitmq \
            -Dtest-broker.A.nodename=rabbit@$(hostname) -Dmaven.javadoc.skip=true \
            -Dca.certificate=./tls-gen/basic/result/ca_certificate.pem \
            -Dclient.certificate=./tls-gen/basic/result/client_$(hostname)_certificate.pem \
            -Dit.test=ClientTestSuite,FunctionalTestSuite,ServerTestSuite,SslTestSuite \
            --no-transfer-progress \
            -Dnet.bytebuddy.experimental=true
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq
